#!/bin/sh

# Enable systemd service
if [ -d /run/systemd/system ] && [ -f /lib/systemd/system/sigmatcpserver.service ]; then
    systemctl daemon-reload
    systemctl enable sigmatcpserver.service
    echo "Systemd service enabled. To start it, run: systemctl start sigmatcpserver"
fi

# Compile Python files
if command -v py3compile >/dev/null 2>&1; then
    py3compile -p python3-hifiberry-dsp
fi

exit 0
