#!/bin/sh

set -e

# Enable systemd service
if [ "$1" = "configure" ]; then
    if [ -d /run/systemd/system ] && [ -f /lib/systemd/system/sigmatcpserver.service ]; then
        systemctl daemon-reload >/dev/null 2>&1 || true
        systemctl enable sigmatcpserver.service >/dev/null 2>&1 || true
        echo "Systemd service enabled. To start it, run: systemctl start sigmatcpserver"
    fi
fi

#DEBHELPER#

exit 0
