#!/bin/sh
set -e

# Stop and disable service before removal
if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    if [ -d /run/systemd/system ] && [ -f /lib/systemd/system/sigmatcpserver.service ]; then
        echo "Stopping and disabling HiFiBerry DSP systemd service"
        systemctl stop sigmatcpserver.service || true
        systemctl disable sigmatcpserver.service || true
    fi
fi

exit 0
